birth1=input("Enter the birth date: ")
birth2=input("Enter the birth date: ")
birth3=input("Enter the birth date: ")
birth4=input("Enter the birth date: ")
birth5=input("Enter the birth date: ")
print("The birth dates entered are:")
print(birth1)   
print(birth2)
print(birth3)
print(birth4)
print(birth5)